name: CI
on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "16.18.0"
      - run: npm ci
      - run: npm audit fix --force
      - run: npm run format:check
      - run: npm test -- --coverage
        env:
          CI: true
